export const DB_NAME="rozgarhub";

export const SECONDS_PER_MINUTE=60;
export const MILLISECONDS_PER_SECOND=1000;

export const OAUTH_EXCHANGE_EXPIRY=10*SECONDS_PER_MINUTE*MILLISECONDS_PER_SECOND;

export const OTP_EXPIRY=10*SECONDS_PER_MINUTE*MILLISECONDS_PER_SECOND;

export const RESET_PASSWORD_TOKEN_EXPIRY=15*SECONDS_PER_MINUTE*MILLISECONDS_PER_SECOND;